server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/storeManagement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
  #    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: com.hubu.gl.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


##Pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #  elasticsearch:
  #    rest:
  #      uris: http://127.0.0.1:9200
  #      username: elastic
  #      password: elastic
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    #确认消息已发送到交换机(Exchange)
#    #确认消息已发送到队列(Queue)--生产者消息确认
#    publisher-returns: true
#    publisher-confirm-type: correlated
#    listener:
#      simple:
#        #        手动确认：manual,none,auto--消费者消息确认
#        acknowledge-mode: manual
#logging:
#  config: classpath:log4j2.xml
##showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug

### 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.hubu.dy127.dao  # 注意：对应实体类的路径



#Elasticsearch 配置
#  spring.elasticsearch.rest.uris=http://127.0.0.1:9200
#  spring.elasticsearch.rest.username=elastic
#  spring.elasticsearch.rest.password=tongyu1956125


